package com.medplus.agreement_tracker_backend.enums;

/**
 * Application permission codes. Stored in {@code rights.code} and issued to users
 * via role assignments. Designed to map cleanly to CAS attributes during SSO integration.
 */
public enum RightCode {
    DASHBOARD_VIEW,
    DRAFT_VIEW_MY,
    DRAFT_VIEW_ALL,
    DRAFT_EDIT_MY,
    DRAFT_EDIT_ALL,
    DRAFT_DELETE_MY,
    DRAFT_DELETE_ALL,
    AGREEMENT_VIEW_MY,
    AGREEMENT_VIEW_ALL,
    AGREEMENT_EDIT_MY,
    AGREEMENT_EDIT_ALL,
    AGREEMENT_SUBMIT_MY,
    AGREEMENT_SUBMIT_ALL,
    AGREEMENT_RENEW_MY,
    AGREEMENT_RENEW_ALL,
    AGREEMENT_REVISE_MY,
    AGREEMENT_REVISE_ALL,
    AGREEMENT_TERMINATE_MY,
    AGREEMENT_TERMINATE_ALL,
    AGREEMENT_IN_PROGRESS_MY,
    AGREEMENT_IN_PROGRESS_ALL,
    AGREEMENT_CREATE,
    AGREEMENT_APPROVE,
    AGREEMENT_REJECT,
    AGREEMENT_CLONE,
    AGREEMENT_TRANSFER,
    MASTER_VIEW,
    MASTER_MANAGE,
    ADMIN_USERS,
    PRICE_OFF_VIEW,
    PRICE_OFF_MANAGE,
    PRICE_OFF_APPROVE,
    COMMERCIAL_PAYOUT_CALCULATE
}
